config/routes.rb
Receta::Application.routes.draw do

  devise_for :users

  resources :users, only: [:show, :index, :update]

  resources :recipes 

  
  get "home/index"
  get "home/about"
  get "home/contact"
  root 'home#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  belongs_to :user

  validates :title, length: { minimum: 3 }, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :recipes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end


  def show
    @recipe = Recipe.find(params[:id])
    @user = current_user
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      flash[:notice] = "Recipe successfully updated."
      redirect_to recipes_path
    else
      flash[:error] = "Error saving your recipe. Please try again."
      render :edit
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "Recipe #{@recipe.title} was successfully created."
      redirect_to @recipe
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      flash[:notice] = "Recipe was deleted successfully."
      redirect_to recipes_path
    else
      #flash[:error] = "There was an error deleting the recipe."
      #redirect_to :show
    end
  end

###########################  PRIVATE  ############################################

  private
  
  def copy 
    @copy = @recipe.dup
    @user.recipes.create(@copy.attributes)
  end

  def recipe_params
    params.require(:recipe).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @recipes = @user.recipes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/contact.html.erb
<h1>Contact</h1>

<a href='https://www.codersclan.net/task/Aguynamedsteve' target='_blank'><img src='https://www.codersclan.net/button/Aguynamedsteve' alt='expert-button' width='205' height='64' style='width: 205px; height: 64px;'></a>

app/views/home/index.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="http://37.media.tumblr.com/c626bdecc3acd91fcc88950c7b9e6b77/tumblr_n164eyaBeD1qitz6do1_500.jpg", class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Welcome to Receta</h1>
          <p>Tasty version Control.</p>
          <pthis is="" an="" example="" layout="" with="" carousel="" that="" uses="" the="" bootstrap="" 3="" styles.<="" small=""><p></p>
          <p><a class="btn btn-lg btn-primary" href="">Learn More</a>
        </p></pthis></div>
      </div>
    </div>
    <div class="item">
      <img src="http://p1.pichost.me/640/24/1475188.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Perfect your recipes</h1>
          <p>Simple to use.</p>
          <p><a class="btn btn-large btn-primary" href="#">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="https://pbs.twimg.com/media/Bobjms0IAAAhUtb.jpg:large" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Never lose another recipe</h1>
          <p>With version control it's easier than ever to find that Casserole recipe that Aunt Patty raved about in 1998.</p>
          <p><a class="btn btn-large btn-primary" href="#">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>  
</div>
<!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="container marketing">
  <!-- START THE FEATURETTES -->
  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSaKxA5CsgPsgMnUW7qGxGZZllu-fA2LnpJCpbcZQJCXQ7Ute_dIg">
    <h2 class="featurette-heading">Feature Rich. <span class="text-muted">It'll blow your mind.</span></h2>
    <p class="lead">Lorem ipsum dolor sit amet, suspendisse sapien cras ac sed dis. Tempus donec, luctus diam.</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-left" src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS4MF1zS6ubIp-SUwcDx6RYxSY9tFIXH9mXx7l2EvtjBUVcRI8s">
    <h2 class="featurette-heading">Clean out your recipe box. <span class="text-muted">Free yourself.</span></h2>
    <p class="lead">Lorem ipsum dolor sit amet, suspendisse sapien cras ac sed dis. Tempus donec, luctus diam.</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ2nADVZLsWetbHVA657J6n2Ktyd7TTAGBeICaoRIPD7_n_Qsdkhg">
    <h2 class="featurette-heading">Start from your last sucess. <span class="text-muted">Track the journey.</span></h2>
    <p class="lead">Lorem ipsum dolor sit amet, suspendisse sapien cras ac sed dis. Tempus donec, luctus diam.</p>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->
</div><!-- /.container -->

app/views/layouts/_column.html.erb
<!-- Three columns of text below the carousel
The is still stock remember to change content before adding -->
  <div class="row">
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>Mobile-first</h2>
      <p>Tablets, phones, laptops. The new 3 promises to be mobile friendly from the start.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>One Fluid Grid</h2>
      <p>There is now just one percentage-based grid for Bootstrap 3. Customize for fixed widths.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>LESS is More</h2>
      <p>Improved support for mixins make the new Bootstrap 3 easier to customize.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
  </div><!-- /.row -->

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb
<p class="pull-right"><a href="#">Back to top</a></p>
<p>&copy; 2014 RECETA -- DESIGN & WEBSITE BY STEVE BARNES</p>

app/views/layouts/_navbar.html.erb
<div class="navbar-wrapper">
  <div class="container">
    <div class="navbar navbar-inverse navbar-static-top">
      
        <div class="navbar-header">
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
        <a class="navbar-brand" href="/">Receta</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/recipes">Recipes</a></li>
            <li><a href="/home/about" >About</a></li>
            <li><a href="/home/contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <div class="pull-right">
            <ul class="nav navbar-nav">
            <% if current_user %>
              <li><a href="/users/:id">Hello <%= current_user.username || current_user.email %></a></li>
              <li><%= link_to edit_user_registration_path, class: 'btn btn-primary btn-xs' do %>
                <span class="glyphicon glyphicon-user"></span>
              <% end %></li>
              <li><%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-xs' do  %>
                <span class="glyphicon glyphicon-log-out"></span>
              <% end %></li>
        
            <% else %>
              <li><a href="/users/sign_in" id="devise">Sign In</a></li>
              <li><a href="/users/sign_up" id="deviseb">Sign Up</a></li>
            <% end %>
          </ul>
          </div>
        </div>

    </div>
  </div><!-- /container -->
</div><!-- /navbar wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receta</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="wrapper">
      <div id="header">
        <nav><%= render partial: 'layouts/navbar' %></nav>
      </div>
      <div id="content">
        <%= render partial: "layouts/flash_messages" %>
        <%= yield %>
      </div>
        <script type="text/javascript">$('.carousel').carousel();</script>
      <div class="footer">
        <%= render partial: 'layouts/footer'  %>
      </div>
    </div>
  </body>
</html>

app/views/recipes/destroy.html.erb
<h1>Destroy recipe</h1>

<h2>destroy button with eventual comfirm and persuade messages</h2>

app/views/recipes/edit.html.erb
<h1><%= @recipe.title %></h1>

  <div>
    <%= form_for @recipe do |f| %>
      Title: <%= f.text_area :title %><br />
      Recipe: <%= f.text_area :body %><br />
      <%= f.submit %>
    <% end %>
  </div>

  <%= link_to "Back", :back %> | <%= link_to "Delete", method: :destroy %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe %> <small>created by</small> <%= recipe.user.username %></li>
  <% end %>
</ul>

<%= link_to 'Home', home_index_path %> | <%= link_to 'New Recipe', new_recipe_path %>  

app/views/recipes/new.html.erb
<h1>New Recipe<h1>


  <div>
    <%= form_for @recipe do |f| %>
      Title: <%= f.text_area :title %><br />
      Recipe: <%= f.text_area :body %><br />
      <%= f.submit %>
    <% end %>
  </div>

  <%= link_to "Back", :back %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<div><%= @recipe.body %></div>

<br />
<%= link_to 'Back', :back %> | <%= link_to 'Home', home_index_path %> | <%= link_to 'Edit', edit_recipe_path %> | <%= link_to "Copy", @recipe.copy %>

app/views/users/show.html.erb
<h1><%= current_user.username %>'s Profile</h1>

<h3>Your Recipes</h3>
  <ul>
    <% @user.recipes.each do |recipe| %>
      <li><%= link_to recipe.title, recipe %></li>
    <% end %>
  </ul>